version: '3'
services:
  db:
    restart: always
    image: postgres:10.3
    environment:
      - POSTGRES_USER=$PGUSER
      - POSTGRES_PASSWORD=$PGPASSWORD
      - POSTGRES_DB=$PGDATABASE
    # Uncomment if I need to connect to DB
    # ports:
    #   - $PGPORT:5432
  onion_or_not_server:
    restart: always
    build: .
    ports:
      - $PORT:8000
    volumes:
      - .:/opt/app
    environment:
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=5432
      - NODE_ENV=development