service:
  name: onion-or-not

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  question:
    handler: question.main
    events:
      - http:
          method: get
          path: question
  answer:
    handler: answer.main
    events:
      - http:
          method: post
          path: answer
